default: &defaults
  user: vzl
  password: password
  adapter: postgresql
  host: localhost
  min_messages: WARNING
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *defaults
  database: toad_development

test:
  <<: *defaults
  database: toad_test

production:
  <<: *defaults
  database: toad_production

staging:
  <<: *defaults
  database: toad_staging
