development:
  secret_key_base: 863e21cd3ab2064ad96c136da5f7aff5259d2cea83efce0ed3be09ae5769b7942b211e88511d1bd6ff8cd3321bd9dee260f7aaa7396afec58fd1eb56236864ae
  # This one is previous
  # armor_api_key: b45de12c647a7984aa074ede2fdaacf4
  # armor_api_secret: ec4eadfb08c4f31e7cbe4eb6cdaaecaa764a4af3efccbb3efb576de6836730f3
  armor_api_key: 70ec913456f4f67a5840cf4d3834372f
  armor_api_secret: 326380d8f2d348e9de44213ebf0d1de8113bb7a7bea0585cbcb0268c56330a83
  armor_partner_id: 160714058317
  # For promisepay
  PROMISEPAY_USERNAME: johnb@toadlane.com
  PROMISEPAY_TOKEN: MDgwMzdjMTA3NmFhYWUyN2U1OTM0NzViNThiMWY0MDU=

  # For synapsepay fly and buy
  SYNAPSEPAY_CLIENT_ID:  id-fb13c910-a846-49e0-a479-26e763bfc62b
  SYNAPSEPAY_CLIENT_SECRET:  secret-b703ba44-2bac-49c6-85f5-3de140742041
  SYNAPSEPAY_WEBHOOK_URL: http://requestb.in/1j6dg2z1

test:
  secret_key_base: 587835be93d7667a6dc45eb82436bd51b8b77f45499fb371ed4d3811c21372c69f7beb5b3be924cc25812f607e2bd9855c55a7182b04af781161114642fd4089
  armor_api_key: b45de12c647a7984aa074ede2fdaacf4
  armor_api_secret: ec4eadfb08c4f31e7cbe4eb6cdaaecaa764a4af3efccbb3efb576de6836730f3
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>


staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  armor_api_key: <%= ENV["ARMOR_API_KEY"] %>
  armor_api_secret: <%= ENV["ARMOR_API_SECRET"] %>
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  armor_api_key: <%= ENV["ARMOR_API_KEY"] %>
  armor_api_secret: <%= ENV["ARMOR_API_SECRET"] %>
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>
