development:
  secret_key_base: 863e21cd3ab2064ad96c136da5f7aff5259d2cea83efce0ed3be09ae5769b7942b211e88511d1bd6ff8cd3321bd9dee260f7aaa7396afec58fd1eb56236864ae
  # This one is previous
  # armor_api_key: b45de12c647a7984aa074ede2fdaacf4
  # armor_api_secret: ec4eadfb08c4f31e7cbe4eb6cdaaecaa764a4af3efccbb3efb576de6836730f3
  armor_api_key: 70ec913456f4f67a5840cf4d3834372f
  armor_api_secret: 326380d8f2d348e9de44213ebf0d1de8113bb7a7bea0585cbcb0268c56330a83
  armor_partner_id: 160714058317
  # For promisepay
  PROMISEPAY_USERNAME: johnb@toadlane.com
  PROMISEPAY_TOKEN: MDgwMzdjMTA3NmFhYWUyN2U1OTM0NzViNThiMWY0MDU=

  # For synapsepay fly and buy
  SYNAPSEPAY_DASHBOARD_URL: https://sandbox.synapsepay.com/api/v3/user/create
  ADMIN_EMAIL_GROUP_VERIFICATION: neha@jyaasa.com

  synapsepay_client_id: client_id_fcc839882e6111e7a29c0230ad3203db
  synapsepay_client_secret: client_secret_5e1dd9aa33e0444298ae10fd3194ddaf
  synapsepay_webhook_url: http://fc9e31b6.ngrok.io/synapsepay/26143155/callback
  synapsepay_escrow_node_id: 59071ddb9802160025b0d633
  synapsepay_escrow_fee_holder_node_id: 59071e139802160026b030c0
  synapsepay_user_id: 59071cd4b72f86002045ceaf
  synapsepay_fingerprint: 8781321799f523327fb8d1f15ffa266d

test:
  secret_key_base: 587835be93d7667a6dc45eb82436bd51b8b77f45499fb371ed4d3811c21372c69f7beb5b3be924cc25812f607e2bd9855c55a7182b04af781161114642fd4089
  armor_api_key: b45de12c647a7984aa074ede2fdaacf4
  armor_api_secret: ec4eadfb08c4f31e7cbe4eb6cdaaecaa764a4af3efccbb3efb576de6836730f3
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>
  synapsepay_client_id: client_id_fcc839882e6111e7a29c0230ad3203db
  synapsepay_client_secret: client_secret_5e1dd9aa33e0444298ae10fd3194ddaf
  synapsepay_webhook_url: http://fc9e31b6.ngrok.io/synapsepay/26143155/callback
  synapsepay_escrow_node_id: 59071ddb9802160025b0d633
  synapsepay_escrow_fee_holder_node_id: 59071e139802160026b030c0
  synapsepay_user_id: 59071cd4b72f86002045ceaf
  synapsepay_fingerprint: 8781321799f523327fb8d1f15ffa266d

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  armor_api_key: <%= ENV["ARMOR_API_KEY"] %>
  armor_api_secret: <%= ENV["ARMOR_API_SECRET"] %>
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>

  synapsepay_client_id:  <%= ENV["SYNAPSEPAY_CLIENT_ID"] %>
  synapsepay_client_secret:  <%= ENV["SYNAPSEPAY_CLIENT_SECRET"] %>
  synapsepay_webhook_url: <%= ENV["SYNAPSEPAY_WEBHOOK_URL"] %>
  synapsepay_escrow_node_id: <%= ENV["SYNAPSEPAY_ESCROW_NODE_ID"] %>
  synapsepay_escrow_fee_holder_node_id: <%= ENV["SYNAPSEPAY_ESCROW_FEE_HOLDER_NODE_ID"] %>
  synapsepay_user_id: <%= ENV["SYNAPSEPAY_APP_USER_ID"] %>
  synapsepay_fingerprint: <%= ENV["SYNAPSEPAY_APP_FINGERPRINT"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  armor_api_key: <%= ENV["ARMOR_API_KEY"] %>
  armor_api_secret: <%= ENV["ARMOR_API_SECRET"] %>
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>

  synapsepay_client_id:  <%= ENV["SYNAPSEPAY_CLIENT_ID"] %>
  synapsepay_client_secret:  <%= ENV["SYNAPSEPAY_CLIENT_SECRET"] %>
  synapsepay_webhook_url: <%= ENV["SYNAPSEPAY_WEBHOOK_URL"] %>
  synapsepay_escrow_node_id: <%= ENV["SYNAPSEPAY_ESCROW_NODE_ID"] %>
  synapsepay_escrow_fee_holder_node_id: <%= ENV["SYNAPSEPAY_ESCROW_FEE_HOLDER_NODE_ID"] %>
  synapsepay_user_id: <%= ENV["SYNAPSEPAY_APP_USER_ID"] %>
  synapsepay_fingerprint: <%= ENV["SYNAPSEPAY_APP_FINGERPRINT"] %>
