development:
  secret_key_base: 863e21cd3ab2064ad96c136da5f7aff5259d2cea83efce0ed3be09ae5769b7942b211e88511d1bd6ff8cd3321bd9dee260f7aaa7396afec58fd1eb56236864ae
  armor_api_key: b45de12c647a7984aa074ede2fdaacf4
  armor_api_secret: ec4eadfb08c4f31e7cbe4eb6cdaaecaa764a4af3efccbb3efb576de6836730f3
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>

test:
  secret_key_base: 587835be93d7667a6dc45eb82436bd51b8b77f45499fb371ed4d3811c21372c69f7beb5b3be924cc25812f607e2bd9855c55a7182b04af781161114642fd4089
  armor_api_key: b45de12c647a7984aa074ede2fdaacf4
  armor_api_secret: ec4eadfb08c4f31e7cbe4eb6cdaaecaa764a4af3efccbb3efb576de6836730f3
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>


staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  armor_api_key: <%= ENV["ARMOR_API_KEY"] %>
  armor_api_secret: <%= ENV["ARMOR_API_SECRET"] %>
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  armor_api_key: <%= ENV["ARMOR_API_KEY"] %>
  armor_api_secret: <%= ENV["ARMOR_API_SECRET"] %>
  armor_partner_id: <%= ENV["ARMOR_PARTNER_ID"] %>